name:                pseudoassembler-compiler
version:             1.2
github:              "JakuJ/pseudoassembler-compiler"
license:             BSD3
author:              "Jakub Janaszkiewicz"
maintainer:          "janaszkiewicz.jakub@gmail.com"
copyright:           "2018 Jakub Janaszkiewicz"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/JakuJ/pseudoassembler-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- process
- directory

library:
  source-dirs: src

executables:
  pseudoassembler-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    - -Wincomplete-patterns
    dependencies:
    - pseudoassembler-compiler

tests:
  pseudoassembler-compiler-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    - -Wincomplete-patterns
    dependencies:
    - pseudoassembler-compiler
